[package]
name    = "sscg_gd"
version = "0.2.0"
authors = ["weictr"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
palette     = "0.5"
gdnative    = "0.7.0"
regex       = "1.3.3"
wlambda     = { path = "../../WLambda" }
euclid      = "0.20.1"

[lib]
crate-type = ["cdylib"]
