[package]
name = "sscg_gd"
version = "0.1.0"
authors = ["weictr"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdnative = { path = "../../other/godot-rust/gdnative" }
euclid   = "0.20.1"

[lib]
crate-type = ["cdylib"]
